### ISSUE TITLE
Arducam driver won't load

### ISSUE THREAD

**Issue by janvrska** [ArduCAM/Arducam_OBISP_MIPI_Camera_Module#12]
I compiled arducam driver on my rpi4 with the current kernel version
(latest "Raspberry Pi OS with desktop", October 30th 2021, kernel 5.10)
after install, driver won't load. I also tried to compile it on ubuntu 20.04 but with same result.

uname -a
`Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`

syslog
```
arducam: disagrees about version of symbol module_layout

raspberrypi kernel: [   31.836125] arducam_vddl: disabling
raspberrypi kernel: [   31.836149] arducam_vdig: disabling
raspberrypi kernel: [   31.836174] arducam_vana: disabling
```

I don't want to downgrade raspberry kernel, Will be glad for help.

**Comment by t-sanders** [comment]
Unfortunately, AFAIK the driver only works with the downgraded Raspbian…

Cheers,
Tom
