### ISSUE TITLE
cannot stat for karnel 4.9.201-tegra

### ISSUE THREAD

**Issue by Alimustoofaa** [ArduCAM/Arducam_OBISP_MIPI_Camera_Module#7]
Arducam OBISP drive cannot start in karnel 4.9.201-tegra
```
install: cannot stat './bin/4.9.201-tegra/arducam.ko': No such file or directory
install: target '/boot/overlays/' is not a directory: No such file or directory
```
Thanks

**Comment by AllaboutJay** [comment]
Hello,

**Comment by AllaboutJay** [comment]
Hello,

Thanks for contacting Arducam.

Please follow the step(automatic driver installation) in the doc: https://www.arducam.com/docs/camera-for-jetson-nano/mipi-camera-modules-for-jetson-nano/driver-installation/

If you have any questions, kindly contact us.
Thanks!

**Comment by Alimustoofaa** [comment]
hay @AllaboutJay, solved. 
Thanks!
